# load zgen
source "${HOME}/.zgen/zgen.zsh"

# if the init script doesn't exist
if ! zgen saved; then

  # specify plugins here
  zgen oh-my-zsh

  zgen oh-my-zsh plugins/z
  zgen load denysdovhan/spaceship-prompt spaceship
  zgen load zsh-users/zsh-syntax-highlighting
  # zgen load zsh-users/zsh-history-substring-search.zsh

  # generate the init script from plugins above
  zgen save
fi

# Pay attention to the '--no-use' flag when
# loading nvm. This cuts zsh loading time by a
# big margin.
export NVM_DIR=~/.nvm
 [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" --no-use

# Add Homebrew sbin to PATH
export PATH="/usr/local/sbin:$PATH"

# Loads bashrc.
if [ -f ~/.bashrc ]; then . ~/.bashrc; fi

# Lazy loads pyenv
export PATH="$HOME/.pyenv/bin:$PATH"
pyenv() {
    eval "$(command pyenv init -)"
    pyenv "$@"
}

# Utility to profile zsh loading time
timezsh() {
  shell=${1-$SHELL}
  for i in $(seq 1 10); do /usr/bin/time $shell -i -c exit; done
}
