# Load Powerlevel9k theme config
if [ -f ~/.zsh_powerlevel9k_config ]; then . ~/.zsh_powerlevel9k_config; fi

# Loads bashrc.
if [ -f ~/.bashrc ]; then . ~/.bashrc; fi

# Load antigen.
source $(brew --prefix)/share/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Spaceship theme.
# antigen theme https://github.com/denysdovhan/spaceship-zsh-theme spaceship

# Powerlevel9k theme.
antigen theme bhilburn/powerlevel9k powerlevel9k

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found
antigen bundle brew
antigen bundle common-aliases
antigen bundle compleat
antigen bundle z
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search ./zsh-history-substring-search.zsh

# Tell Antigen that you're done.
antigen apply
export NVM_DIR=~/.nvm
 [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Add Homebrew sbin to PATH
export PATH="/usr/local/sbin:$PATH"
