# Git aliases
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias go='git checkout '
alias gk='gitk --all&'
alias gx='gitx --all'
alias gci='git ci -m '
alias gp='git push -u origin master'

# Remap rm to use trash, safety net against being very sleepy
alias rm=trash

# Remap vim and vi commands to always run neovim(nvim)
alias nvim=~/nvim-osx64/bin/nvim
alias vim=nvim
alias vi=nvim

# ls replacement
alias l='exa --icons'
alias ll='l -l --icons --git'
alias lt='ll --tree'
alias la='ll -a'
alias lat='ll -a --tree'
alias tree='l --git-ignore --icons --tree'
