# Defines user config folder
export XDG_CONFIG_HOME=~/.config

# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.5/bin:${PATH}"
export PATH

[[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile

# Add bash aliases.
if [ -f ~/.bash_aliases ]; then
    source ~/.bash_aliases
fi

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Add home folder to path, this is useful for vim 'go to file' feature.
export PATH="$PATH:$HOME"

# Add RVM to PATH for scripting
export PATH="$PATH:$HOME/.rvm/bin"

# Override apple git with brew git.
export PATH="/usr/local/bin:${PATH}"
alias ic="ibmcloud"
