if [ -f ~/.bashrc ]; then . ~/.bashrc; fi
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# Add mysql and valgrind to PATH
export PATH=${PATH}:/usr/local/mysql/bin:/usr/local/Cellar/valgrind/3.11.0/bin
eval $(/usr/libexec/path_helper -s)
